In the CI workflow, merged build, lint and testing jobs into one

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,11 +18,11 @@ on:
       - '**'
 
 env:
-  PRIMARY_NODE_VERSION: 12
+  NODE_VERSION: 12
 
 jobs:
-  typecheck:
-    name: Typecheck
+  build-and-test:
+    name: Build and test
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -33,99 +33,10 @@ jobs:
       - name: echo github.ref
         run: echo ${{ github.ref }}
 
-      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
+      - name: Use Node.js ${{ env.NODE_VERSION }}
         uses: actions/setup-node@v1
         with:
-          node-version: ${{ env.PRIMARY_NODE_VERSION }}
-
-      - name: Get yarn cache directory path
-        id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-
-      - uses: actions/cache@v1
-        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
-        with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
-
-      - name: Install dependencies
-        run: |
-          yarn --ignore-engines --frozen-lockfile --ignore-scripts
-          yarn lerna:init
-          yarn check:clean-workspace-after-install
-
-      - name: Build
-        run: |
-          yarn build
-
-  test_on_primary_node_version:
-    name: Unit tests
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        with:
-          token: ${{ secrets.GH_AUTH_TOKEN }}
-
-      - name: echo github.ref
-        run: echo ${{ github.ref }}
-
-      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{ env.PRIMARY_NODE_VERSION }}
-
-      - name: Get yarn cache directory path
-        id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-
-      - uses: actions/cache@v1
-        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
-        with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
-
-      - name: Install dependencies
-        run: |
-          yarn --ignore-engines --frozen-lockfile --ignore-scripts
-          yarn lerna:init
-          yarn check:clean-workspace-after-install
-
-      - name: Build
-        run: |
-          yarn build
-
-      - name: Run unit tests
-        run: yarn test
-        env:
-          CI: true
-
-
-      - name: Publish code coverage report
-        uses: codecov/codecov-action@v1
-        with:
-          yml: ./codecov.yml
-          token: ${{ secrets.CODECOV_TOKEN }}
-          flags: unittest
-          name: codecov
-
-  linting_and_style:
-    name: Code style and lint
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        with:
-          token: ${{ secrets.GH_AUTH_TOKEN }}
-
-      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{ env.PRIMARY_NODE_VERSION }}
+          node-version: ${{ env.NODE_VERSION }}
 
       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
@@ -144,20 +55,25 @@ jobs:
         run: |
           yarn --ignore-engines --frozen-lockfile --ignore-scripts
           yarn lerna:init
-          yarn check:clean-workspace-after-install
 
       - name: Build
-        run: |
-          yarn build
+        run: yarn build
+
+      - name: Run unit tests
+        run: yarn test
+        env:
+          CI: true
 
       - name: Lint code
-        run: yarn lint
+        run: yarn lint:fix
 
+      - name: Check for code changes
+        run: yarn check:clean-workspace-after-install
 
-  publish_canary_version:
-    name: Publish the latest code as a canary version
+  publish-canary-version:
+    name: Publish canary version
     runs-on: ubuntu-latest
-    needs: [typecheck, test_on_primary_node_version, linting_and_style]
+    needs: [build-and-test]
     if: github.ref == 'refs/heads/master'
     steps:
       - name: Checkout code
@@ -165,15 +81,26 @@ jobs:
         with:
           token: ${{ secrets.GH_AUTH_TOKEN }}
 
+      - name: Verify head of master hasn't changed
+        run: |
+          # We ensure that the latest commit on master is still the one we expected when
+          # we started the release job, otherwise we exit
+          if [ "$GITHUB_SHA" != "$(git rev-parse --verify HEAD)" ]; then
+              echo "ERROR: The commit SHA at the HEAD of master has changed"
+              echo "Expected: $GITHUB_SHA"
+              echo "Actual: $(git rev-parse --verify HEAD)"
+              exit 1;
+          fi
+
       # Fetch all history for all tags and branches in this job because lerna needs it
       - name: Fetch full Git history
         run: |
           git fetch --prune --unshallow
 
-      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
+      - name: Use Node.js ${{ env.NODE_VERSION }}
         uses: actions/setup-node@v1
         with:
-          node-version: ${{ env.PRIMARY_NODE_VERSION }}
+          node-version: ${{ env.NODE_VERSION }}
           registry-url: https://registry.npmjs.org/
 
       - name: Get yarn cache directory path
@@ -195,8 +122,7 @@ jobs:
           yarn check:clean-workspace-after-install
 
       - name: Build
-        run: |
-          yarn build
+        run: yarn build
 
       - name: Publish all packages to npm
         run: npx lerna publish --loglevel=verbose --canary --exact --force-publish --yes
